server:
  port: 8080
spring:
  application:
    name: posthub

  datasource:
    url: jdbc:postgresql://localhost:5432/posthub
    username: postgres
    password: possql312
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: localhost
    port: 6379
    password: possql312
